from __future__ import annotations

from typing import Any, Callable, Mapping, MutableMapping, Protocol, Sequence

from .search_task_policy import SearchTaskPolicy
from .seed_list_parser import SeedListParser
from .seed_scan_policy import SeedScanPolicy

Record = dict[str, Any]
NumberParser = Callable[[Any], Any]


class CollectionAdapter(Protocol):
    """Domain rules consumed by the source-neutral collection orchestration."""

    @property
    def source_platform(self) -> str: ...
    @property
    def collects_avm_risk(self) -> bool: ...
    @property
    def bootstraps_legacy_search_tasks(self) -> bool: ...
    @property
    def search_task_policy(self) -> SearchTaskPolicy: ...
    @property
    def seed_scan_policy(self) -> SeedScanPolicy: ...
    @property
    def analysis_profile(self) -> AnalysisProfile: ...

    def create_seed_list_parser(self, legacy_probe: Any) -> SeedListParser: ...

    def item_id(self, item: Mapping[str, Any]) -> str: ...

    def build_seed_record(
        self,
        item: Mapping[str, Any],
        *,
        parse_number: NumberParser,
        safe_int: NumberParser,
    ) -> Record: ...

    def accepts_seed(
        self, item: Mapping[str, Any], record: Mapping[str, Any]
    ) -> bool: ...

    def sync_record(self, record: MutableMapping[str, Any]) -> None: ...

    def build_storage_record(self, record: Record) -> Record: ...

    def partition_key(self, record: Mapping[str, Any]) -> str: ...

    def prepare_detail_record(
        self,
        record: MutableMapping[str, Any],
        *,
        existing: Mapping[str, Any],
        item_id: str,
    ) -> None: ...

    def accepts_detail(self, record: Mapping[str, Any]) -> bool: ...

    def retry_reason(self, record: Mapping[str, Any]) -> str | None: ...

    def finalize_detail_record(self, record: MutableMapping[str, Any]) -> None: ...

    def archive_date(self, record: Mapping[str, Any]) -> Any: ...

    def source_url(self, record: Mapping[str, Any]) -> str | None: ...

    def quality_summary(self, record: Mapping[str, Any]) -> str: ...

    def location_prompt(self, *, address: str, title: str) -> str | None: ...


class DetailExtractor(Protocol):
    """Source-neutral AI/detail parser used by the detail lifecycle."""

    def extract(self, content: str, *, item_id: str | None = None) -> str: ...


class AnalysisProfile(Protocol):
    """Field policy for evidence-based multi-model AI archiving."""

    @property
    def money_fields(self) -> frozenset[str]: ...
    @property
    def area_fields(self) -> frozenset[str]: ...
    @property
    def ratio_fields(self) -> frozenset[str]: ...
    @property
    def count_fields(self) -> frozenset[str]: ...
    @property
    def boolean_fields(self) -> frozenset[str]: ...
    @property
    def datetime_fields(self) -> frozenset[str]: ...
    @property
    def derived_fields(self) -> frozenset[str]: ...
    @property
    def system_fields(self) -> frozenset[str]: ...
    @property
    def high_risk_fields(self) -> frozenset[str]: ...
    @property
    def field_keywords(self) -> Mapping[str, Sequence[str]]: ...

    def adjudication_prompt(
        self,
        *,
        item_id: str,
        conflicts: Mapping[str, Any],
        candidates: Sequence[Mapping[str, Any]],
        source_text: str,
    ) -> str: ...

    def derive_final_fields(self, field_values: MutableMapping[str, Any]) -> None: ...
